version: '3.8'

services:
  htmx:
    build:
      context: ./
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules # Prevents overwriting the node_modules folder
